sudo: required
dist: xenial

language: node_js
node_js:
  - 'lts/erbium'

matrix:
  include:
    - os: osx
      osx_image: xcode10.1

    - os: linux
      dist: xenial
      services:
        - xvfb
      addons:
        apt:
          packages:
            - libxtst-dev

script:
  - ./build.sh

deploy:
  - provider: script
    script:
      - cd electron-app && yarn deploy
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script:
      - cd electron-app && yarn dist
    skip_cleanup: true
    on:
      tags: false
      all_ranches: true
