language: node_js
node_js:
  - 'lts/erbium'

install:
  - yarn install

script:
  - ./build.sh && cd electron-app && yarn dist

deploy:
  provider: script
  script:
    - cd electron-app && yarn deploy
  skip_cleanup: true
  on:
    tags: true
