sudo: required
dist: xenial

language: node_js
node_js:
  - 'lts/erbium'

install:
  - sudo apt-get install --no-install-recommends -y libopenjp2-tools
  - sudo apt-get install wine32 wine64
  - yarn install

script:
  - ./build.sh

deploy:
  - provider: script
    script:
      - cd electron-app && yarn deploy
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script:
      - cd electron-app && yarn dist
    skip_cleanup: true
    on:
      tags: false
      all_ranches: true
