sudo: required
dist: xenial

language: node_js
node_js:
  - 'lts/erbium'

install:
  - sudo dpkg --add-architecture i386
  - wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
  - sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  - sudo apt install --install-recommends winehq-stable
  - wine --version
  - yarn install

script:
  - ./build.sh

deploy:
  - provider: script
    script:
      - cd electron-app && yarn deploy
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script:
      - cd electron-app && yarn dist
    skip_cleanup: true
    on:
      tags: false
      all_ranches: true
